Code to support fsdb
Bhushan-Jagtap-2013/MicroFS pull request #3
Opened 2017-03-14 00:17 UTC by vishalkudale92

2017-03-14 00:55 UTC, Bhushan-Jagtap-2013 requested changes

2017-03-14 00:55 UTC, Bhushan-Jagtap-2013 commented on cmds/fsdb.c
> +	lseek(devfd,((block_no*MFS_BLOCKSIZE)+offset),SEEK_SET);
Please remove this comment

2017-03-14 00:55 UTC, Bhushan-Jagtap-2013 commented on cmds/fsdb.c
> +	printf("msb_magic                :0x%x\n",usp->msb_magic);
Please you \t instead of spaces to align text

2017-03-14 00:55 UTC, Bhushan-Jagtap-2013 commented on cmds/fsdb.c
> +//	printf("\nInode numner : %d \n",inum);
Remove  comment

2017-03-14 00:55 UTC, Bhushan-Jagtap-2013 commented on cmds/fsdb.c
> +	printf("mi_gid             : %d\n",uip->mi_gid);
use \t instead of space

2017-03-14 00:55 UTC, Bhushan-Jagtap-2013 commented on cmds/fsdb.c
> +		if(i%4==0)
I will prefer to print a table like this

block number :  1          2
address           :   4213   92340

2017-03-14 00:55 UTC, Bhushan-Jagtap-2013 commented on cmds/fsdb.c
> +	if(strcmp(argv[4],"inode")==0)
Please add one more entry here for directory entry 
input : address of dir entry block
output : directory entries

2017-03-14 03:27 UTC, vishalkudale92 commented on cmds/fsdb.c
> +	lseek(devfd,((block_no*MFS_BLOCKSIZE)+offset),SEEK_SET);
Done

2017-03-14 03:27 UTC, vishalkudale92 commented on cmds/fsdb.c
> +	printf("msb_magic                :0x%x\n",usp->msb_magic);
Done

2017-03-14 03:27 UTC, vishalkudale92 commented on cmds/fsdb.c
> +//	printf("\nInode numner : %d \n",inum);
Done

2017-03-14 03:27 UTC, vishalkudale92 commented on cmds/fsdb.c
> +	printf("mi_gid             : %d\n",uip->mi_gid);
Done

2017-03-14 03:28 UTC, vishalkudale92 commented on cmds/fsdb.c
> +		if(i%4==0)
Done.

2017-03-14 03:28 UTC, vishalkudale92 commented on cmds/fsdb.c
> +	if(strcmp(argv[4],"inode")==0)
Didn't get you. will discuss on this.

2017-03-14 17:01 UTC, vishalkudale92 commented on cmds/fsdb.c
> +	if(strcmp(argv[4],"inode")==0)
Done

2017-04-18 13:38 UTC, Bhushan-Jagtap-2013 approved these changes

2017-04-18 13:39 UTC, Bhushan-Jagtap-2013 commented
Looks good. Need some changes but related for code formatting. We will give second round of code refactoring later.

2017-04-18 13:39 UTC, merged